#!/usr/bin/perl

print "Content-type: text/html\n\n";
print "<html><h1>Hello!</h1></html>\n";

#funstions map and grep not actually loops but not

@array = (1..10);
map {$_ = $_*2} (@array);
print "@array\n";


@array = qw(apple bees banana grape);
map {$_ = uc($_)}(@array);
print "@array\n";

#grep matches items with criteria in array
@array = (1..10);
@array2 = grep {$_ > 5} (@array);
print "@array2\n";

#'~=' is the perl binding operator used to check string or modify it amazing!!!
#'!~ is ulta of the above operator'
@array = qw(apple bees banana granpe);
@array2 = grep {$_ =~ "n"} @array;
print "@array2\n";

@array = qw(apple bees banana granpe);
@array2 = grep {$_ !~ "n"} @array;
print "@array2\n";




