#!/usr/bin/perl

print "Content-type: text/html\n\n";
print "<html><h1>Hello!</h1></html>\n";

#operators and precedents

$sum = 4 + 3;
print "$sum\n";

$sum = 4 - 3;
print "$sum\n";

$sum = 4 * 3;
print "$sum\n";

$sum = int(4 / 3);
print "$sum\n";

$sum = 4 + 3 + 9;
print "$sum\n";

#multiplication has precendent over addition
$sum = 4 + 3 * 9;
print "$sum\n";

#another way here
$sum = (4 + 3) * 9;
print "$sum\n";

#division also has precendent over addition
$sum = 4 + 3 / 2;
print "$sum\n";

#if addition precendence over division
$sum = (4 + 3) / 2;
print "$sum\n";

$num1 = 10;
$num2 = 10;
print $num1."\n";
print $num1++."\n";
print ++$num2."\n";
print $num1."\n";


$num1 = 10;
$num2 = 10;
print $num1."\n";
print $num1--."\n";
print --$num2."\n";
print $num1."\n";

print $num1.$num2.$num1."hhahaha\n";

$letter = "a";
$letter++;
print "$letter\n";

$letter = "z";
$letter++;
print "$letter\n";

$letter = "zz";
$letter++;
print "$letter\n";

$letter = "C";
$letter++;
print "$letter\n";

#doesnt work with --!!! :(
$letter = "a";
$letter--;
print "$letter\n";


































